name: Guacamole
version: "1.5.9"
slug: guacamole
description: Apache Guacamole remote desktop gateway
arch:
  - aarch64
startup: services
boot: auto
panel_icon: mdi:remote-desktop
map:
  - data:rw
host_network: false
init: false
ports:
  8080/tcp: 8321
  webui: http://[HOST]:[PORT]/guacamole/
options:
  db_user: guacamole
  db_password: changeme
  admin_password: guacadmin
schema:
  db_user: str
  db_password: password
  admin_password: password
