name: Guacamole
version: "1.5.5"
slug: guacamole
description: Apache Guacamole remote desktop gateway
arch:
  - amd64
  - arm64
startup: services
boot: auto
ingress: true
ingress_port: 8080
ingress_entry: /guacamole/
panel_icon: mdi:remote-desktop
map:
  - data:rw
host_network: false
init: false
ports:
  8080/tcp: 8080
webui: http://[HOST]:[PORT:8080]/guacamole/
options:
  db_user: guacamole
  db_password: changeme
schema:
  db_user: str
  db_password: password
