name: Guacamole
version: "1.6.0-14"
slug: guacamole
description: Apache Guacamole remote desktop gateway
arch:
  - aarch64
startup: services
boot: auto
panel_icon: mdi:remote-desktop
logo: logo.png
icon: icon.png
host_network: false
init: false
ports:
  8080/tcp: 8321
webui: http://[HOST]:[PORT:8321]/guacamole/
options:
  db_user: guacamole
  db_password: changeme
  admin_password: guacadmin
schema:
  db_user: str
  db_password: password
  admin_password: password
