name: Apache Guacamole
version: "1.6.0-31"
slug: guacamole
description: Apache Guacamole remote desktop gateway with support for RDP, VNC, SSH and Telnet protocols
url: https://guacamole.apache.org/
arch:
  - aarch64
startup: services
boot: auto
panel_icon: mdi:remote-desktop
logo: logo.png
icon: icon.png
host_network: false
init: false
ports:
  8080/tcp: 8321
webui: http://[HOST]:[PORT:8321]/guacamole/
